import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const html = await readFile("public/index.html", "utf8");
const js = await readFile("public/app.js", "utf8");
const css = await readFile("public/styles.css", "utf8");
const installer = await readFile("public/install-statusline.sh", "utf8");
const statusLineHelper = await readFile("public/builderperks-statusline.sh", "utf8");
const extensionContent = await readFile("../extension/content.js", "utf8");
const extensionPopup = await readFile("../extension/popup.js", "utf8");
const extensionManifest = await readFile("../extension/manifest.json", "utf8");
const netlifyConfig = await readFile("netlify.toml", "utf8");
const zippedContent = (await execFileAsync("unzip", ["-p", "public/builderperks-extension-beta.zip", "content.js"])).stdout;
const zippedPopup = (await execFileAsync("unzip", ["-p", "public/builderperks-extension-beta.zip", "popup.js"])).stdout;
const zippedManifest = (await execFileAsync("unzip", ["-p", "public/builderperks-extension-beta.zip", "manifest.json"])).stdout;

assert.match(html, /BuilderPerks/);
assert.match(html, /Advertiser/);
assert.match(html, /I'm a builder/);
assert.match(html, /I'm an advertiser/);
assert.match(html, /I publish a devtool/);
assert.match(html, /Opt-in devtool ad network beta/);
assert.match(html, /Publishers can earn only from approved advertiser demand/);
assert.match(html, /never raw prompts or personal data/);
assert.match(html, /Works today/);
assert.match(html, /Real users do not have to wait for a third-party ad network/);
assert.match(html, /Show useful ads now/);
assert.match(html, /Get builders using it/);
assert.match(html, /Convert proof into demand/);
assert.match(html, /60-second demo/);
assert.match(html, /Assisted pilot/);
assert.match(html, /Surface preset/);
assert.match(html, /Terminal status line/);
assert.match(html, /Allowed topics/);
assert.match(html, /Share kit/);
assert.match(html, /Copy builder post/);
assert.match(html, /Copy advertiser DM/);
assert.match(html, /Copy publisher ask/);
assert.match(html, /Get live in one pass/);
assert.match(html, /Install flow/);
assert.match(html, /Add surface/);
assert.match(html, /Reserve pilot/);
assert.match(html, /First-run test/);
assert.match(html, /Use this checklist when testing on your own computer/);
assert.match(html, /Terminal proof/);
assert.match(html, /Status-line test/);
assert.match(html, /Browser proof/);
assert.match(html, /Chrome extension for Claude or ChatGPT tabs/);
assert.match(html, /Show first card now/);
assert.match(html, /active AI workspace/);
assert.match(html, /Feedback proof/);
assert.match(html, /Seamless workflow/);
assert.match(html, /No separate app\. Put one sponsored line where you already work\./);
assert.match(html, /One install should work where builders already spend time/);
assert.match(html, /Terminal or Claude Code/);
assert.match(html, /No separate app is required/);
assert.match(html, /Add browser AI only if useful/);
assert.match(html, /Browser AI/);
assert.match(html, /Terminal/);
assert.match(html, /IDE/);
assert.match(html, /Seamless bar/);
assert.match(html, /mainstream, high-value, regulated, and restricted lanes/);
assert.match(html, /gambling\/iGaming/);
assert.match(html, /Raw impressions and estimated earnings are directional only/);
assert.match(css, /path-router/);
assert.match(css, /works-grid/);
assert.match(css, /demand-status/);
assert.match(css, /demo-flow/);
assert.match(css, /share-grid/);
assert.match(css, /flow-grid/);
assert.match(css, /first-run-grid/);
assert.match(css, /workflow-grid/);
assert.match(css, /workflow-pass/);
assert.match(css, /truth-grid/);
assert.match(css, /command-heading/);
assert.match(js, /submitPlacement/);
assert.match(js, /loadPlacements/);
assert.match(js, /submitFeedback/);
assert.match(js, /submitProofSession/);
assert.match(js, /submitBuilder/);
assert.match(js, /submitPublisher/);
assert.match(js, /setupShareKit/);
assert.match(js, /setupCopyCommands/);
assert.match(js, /navigator\.clipboard\.writeText/);
assert.match(js, /scrollIntoView/);
assert.match(js, /escapeHtml/);
assert.match(js, /trackUrl/);
assert.match(js, /loadStats/);
assert.match(js, /loadDemandStatus/);
assert.match(js, /providerStatus/);
assert.match(js, /fallbackPlacement/);
assert.match(js, /verified workflow sessions/);
assert.match(html, /Record proof session/);
assert.match(html, /Saw one labeled sponsored line during a real workflow/);
assert.match(js, /need this/);
assert.match(js, /hidden categories/);
assert.match(html, /install-statusline\.sh/);
assert.match(html, /statusline\.sh/);
assert.match(html, /~\/\.builderperks\/config\.env/);
assert.match(html, /BUILDERPERKS_DEBUG=1 ~\/\.builderperks\/statusline\.sh/);
assert.match(html, /"statusLine": \{ "type": "command", "command": "~\/\.builderperks\/statusline\.sh" \}/);
assert.match(html, /bp_pub_token/);
assert.match(html, /less install-statusline\.sh/);
assert.match(html, /not from paying users to view or click ads/);
assert.match(html, /not paid-to-watch traffic/);
assert.match(html, /BUILDERPERKS_VALUE_MODE/);
assert.match(html, /allowedCategories/);
assert.match(html, /BuilderPerks sponsored line/);
assert.match(html, /problemMatcher/);
assert.match(html, /VS Code and Cursor/);
assert.match(js, /install-statusline\.sh/);
assert.match(js, /publisherTopicKeywords/);
assert.match(js, /allowedTopics/);
assert.match(js, /surfacePreset/);
assert.match(js, /publisherToken/);
assert.match(js, /proofSessionNonces/);
assert.match(js, /proofSessionSignature/);
assert.match(js, /bash -s -- \$\{shellArg\(publisherId\)\} \$\{shellArg\(publisherToken\)\} \$\{shellArg\(selectedKeywords\)\} \$\{shellArg\(selectedSurface\)\}/);
assert.match(js, /Inspect first if you do not run curl \| bash/);
assert.match(js, /Claude Code settings snippet/);
assert.match(js, /VS Code \/ Cursor task snippet/);
assert.match(js, /Debug setup if blank/);
assert.match(js, /~\/\.builderperks\/config\.env/);
assert.match(js, /publisher-earnings-count/);
assert.match(installer, /statusline\.sh/);
assert.match(installer, /config\.env/);
assert.match(installer, /BUILDERPERKS_PUBLISHER_ID=\$\(shell_quote "\$PUBLISHER_ID"\)/);
assert.match(installer, /BUILDERPERKS_PUBLISHER_TOKEN=\$\(shell_quote "\$PUBLISHER_TOKEN"\)/);
assert.match(installer, /chmod 600 "\$CONFIG_FILE"/);
assert.match(installer, /BUILDERPERKS_DEBUG=1 \$INSTALL_DIR\/statusline\.sh/);
assert.match(installer, /Claude Code settings snippet/);
assert.match(installer, /preference keywords/);
assert.match(installer, /less install-statusline\.sh/);
assert.match(statusLineHelper, /CONFIG_FILE/);
assert.match(statusLineHelper, /\. "\$CONFIG_FILE"/);
assert.match(statusLineHelper, /ENV_API_URL/);
assert.match(statusLineHelper, /BUILDERPERKS_PUBLISHER_TOKEN/);
assert.match(statusLineHelper, /BUILDERPERKS_DEBUG/);
assert.match(statusLineHelper, /request failed/);
assert.match(statusLineHelper, /debug_detail = data\.get\("reason"\) or data\.get\("error"\) or data\.get\("message"\) or ""/);
assert.match(statusLineHelper, /BUILDERPERKS_PUBLISHER_ID/);
assert.match(statusLineHelper, /BUILDERPERKS_BLOCKED_KEYWORDS/);
assert.match(statusLineHelper, /BUILDERPERKS_ALLOWED_CATEGORIES/);
assert.match(statusLineHelper, /BUILDERPERKS_BLOCKED_CATEGORIES/);
assert.match(statusLineHelper, /BUILDERPERKS_VALUE_MODE/);
assert.match(statusLineHelper, /urlopen\(url, timeout=5\)/);
assert.match(await readFile("netlify/functions/placements.mts", "utf8"), /paymentStatus = "checkout_ready"/);
assert.match(await readFile("netlify/functions/placements.mts", "utf8"), /checkoutError/);
assert.match(await readFile("netlify/functions/builders.mts", "utf8"), /BuilderSignup/);
assert.match(await readFile("netlify/functions/publishers.mts", "utf8"), /Publisher/);
const adStream = await readFile("netlify/functions/ad-stream.mts", "utf8");
const publishersFunction = await readFile("netlify/functions/publishers.mts", "utf8");
const providerStatus = await readFile("netlify/functions/provider-status.mts", "utf8");
const providerConfig = await readFile("netlify/functions/_providers.mts", "utf8");
const partnerFeeds = await readFile("netlify/functions/_partner_feeds.mts", "utf8");
assert.match(adStream, /estimatedPublisherEarningsUsd/);
assert.match(adStream, /Publisher token is required/);
assert.match(adStream, /publisher_hourly_cap/);
assert.match(publishersFunction, /secretToken\("bp_pub"\)/);
assert.match(publishersFunction, /tokenNotice/);
assert.match(publishersFunction, /publicPublisher/);
assert.match(adStream, /demandStatusForPlacement/);
assert.match(adStream, /builderperks_seed/);
assert.match(adStream, /blockedKeywords/);
assert.match(adStream, /matchesBlockedPreference/);
assert.match(adStream, /redactSensitiveKeywordSource/);
assert.match(adStream, /api\[_-\]\?key\|token\|secret\|password\|authorization\|bearer/);
assert.match(adStream, /\/Users\|\\\/home\|\\\/Volumes/);
assert.match(adStream, /CATEGORY_PROFILES/);
assert.match(adStream, /allowedCategories/);
assert.match(adStream, /blockedCategories/);
assert.match(adStream, /providerLanes/);
assert.match(adStream, /cybersecurity/);
assert.match(adStream, /ecommerce/);
assert.match(adStream, /real_estate/);
assert.match(adStream, /sweepstakes/);
assert.match(adStream, /crypto/);
assert.match(adStream, /dating/);
assert.match(adStream, /regulated_partner/);
assert.match(adStream, /restricted_partner/);
assert.match(adStream, /configuredPartnerIntegrations/);
assert.match(adStream, /approvedPartnerFeedPlacements/);
assert.match(providerStatus, /approvedPartnerFeedSources/);
assert.match(partnerFeeds, /BUILDERPERKS_APPROVED_PARTNER_FEED_URLS/);
assert.match(partnerFeeds, /demandSource: "approved_partner"/);
assert.match(providerConfig, /BUILDERPERKS_ETHICALADS_PUBLISHER_ID/);
assert.match(providerConfig, /BUILDERPERKS_PROVIDER_APPROVED_/);
assert.match(providerConfig, /credentialsConfigured/);
assert.match(providerConfig, /providerApproved/);
assert.match(providerConfig, /canServeNow = credentialsConfigured && providerApproved/);
assert.match(providerConfig, /BUILDERPERKS_CARBON_ZONE_KEY/);
assert.match(providerConfig, /BUILDERPERKS_CARBON_CLI_SDK_KEY/);
assert.match(providerConfig, /BUILDERPERKS_BSA_ADS_URL/);
assert.match(providerConfig, /BUILDERPERKS_BSA_NEWSLETTER_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_ADBUTLER_JSON_URL/);
assert.match(providerConfig, /BUILDERPERKS_KEVEL_NETWORK_ID/);
assert.match(providerConfig, /BUILDERPERKS_GOOGLE_AD_MANAGER_NETWORK_CODE/);
assert.match(providerConfig, /BUILDERPERKS_ADMOB_APP_ID/);
assert.match(providerConfig, /BUILDERPERKS_ADGLARE_JSON_URL/);
assert.match(providerConfig, /BUILDERPERKS_EPOM_API_URL/);
assert.match(providerConfig, /BUILDERPERKS_BROADSTREET_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_REVIVE_ZONE_URL/);
assert.match(providerConfig, /BUILDERPERKS_ADSBIND_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_CHATADS_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_NEXAD_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_ARYEL_IN_CHAT_KEY/);
assert.match(providerConfig, /BUILDERPERKS_MICROSOFT_CHAT_ADS_KEY/);
assert.match(providerConfig, /BUILDERPERKS_IDLEN_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_PAVED_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_BEEHIIV_SPONSORSHIP_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_META_AUDIENCE_PLACEMENT_ID/);
assert.match(providerConfig, /BUILDERPERKS_APPLOVIN_SDK_KEY/);
assert.match(providerConfig, /BUILDERPERKS_CAS_AI_APP_ID/);
assert.match(providerConfig, /BUILDERPERKS_YANGO_ADS_APP_ID/);
assert.match(providerConfig, /BUILDERPERKS_PARTNERSTACK_FEED_URL/);
assert.match(providerConfig, /BUILDERPERKS_IMPACT_ACCOUNT_SID/);
assert.match(providerConfig, /BUILDERPERKS_CJ_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_RAKUTEN_ADVERTISING_TOKEN/);
assert.match(providerConfig, /BUILDERPERKS_PARTNERIZE_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_FLEXOFFERS_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_AWIN_API_TOKEN/);
assert.match(providerConfig, /BUILDERPERKS_COINZILLA_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_BITMEDIA_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_COINTRAFFIC_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_A_ADS_UNIT_ID/);
assert.match(providerConfig, /BUILDERPERKS_ADEX_PLACEMENT_ID/);
assert.match(providerConfig, /BUILDERPERKS_INFORMA_TECHTARGET_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_FOUNDRY_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_TECHNOLOGYADVICE_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_MADISON_LOGIC_ACCOUNT_ID/);
assert.match(providerConfig, /BUILDERPERKS_OUTBRAIN_WIDGET_ID/);
assert.match(providerConfig, /BUILDERPERKS_TABOOLA_PLACEMENT_ID/);
assert.match(providerConfig, /BUILDERPERKS_MGID_WIDGET_ID/);
assert.match(providerConfig, /BUILDERPERKS_TRIPLELIFT_PLACEMENT_ID/);
assert.match(providerConfig, /BUILDERPERKS_REVCONTENT_WIDGET_ID/);
assert.match(providerConfig, /BUILDERPERKS_SOVRN_SITE_ID/);
assert.match(providerConfig, /BUILDERPERKS_PUBMATIC_PUBLISHER_ID/);
assert.match(providerConfig, /BUILDERPERKS_MAGNITE_PUBLISHER_ID/);
assert.match(providerConfig, /BUILDERPERKS_INDEX_EXCHANGE_PUBLISHER_ID/);
assert.match(providerConfig, /BUILDERPERKS_AMAZON_PUBLISHER_SERVICES_ID/);
assert.match(providerConfig, /BUILDERPERKS_EXOCLICK_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_TRAFFICJUNKY_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_TRAFFICSTARS_SPOT_ID/);
assert.match(providerConfig, /BUILDERPERKS_JUICYADS_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_PLUGRUSH_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_ADNIUM_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_EROADVERTISING_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_TWINRED_PUBLISHER_ID/);
assert.match(providerConfig, /BUILDERPERKS_TRAFFICFACTORY_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_TRAFFICSHOP_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_CLICKADU_SKIM_URL/);
assert.match(providerConfig, /BUILDERPERKS_HILLTOPADS_DIRECT_URL/);
assert.match(providerConfig, /BUILDERPERKS_ADMAVEN_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_CRAKREVENUE_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_CPAMATICA_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_TRAFEE_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_MOBIPIUM_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_CLICKDEALER_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_MAXBOUNTY_API_KEY/);
assert.match(providerConfig, /BUILDERPERKS_ZEYDOO_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_RICHADS_DIRECT_URL/);
assert.match(providerConfig, /BUILDERPERKS_PROPELLERADS_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_ADSTERRA_SMARTLINK_URL/);
assert.match(providerConfig, /BUILDERPERKS_MONDIAD_ZONE_ID/);
assert.match(providerConfig, /BUILDERPERKS_XBET_PARTNERS_ID/);
assert.match(providerConfig, /BUILDERPERKS_BETWAY_PARTNERS_ID/);
assert.match(providerConfig, /BUILDERPERKS_PINUP_PARTNERS_ID/);
assert.match(providerConfig, /tool_native_network/);
assert.match(providerConfig, /affiliate_backfill/);
assert.match(providerConfig, /website_app_network/);
assert.match(providerConfig, /mobile_app_network/);
assert.match(providerConfig, /ai_native_network/);
assert.match(providerConfig, /developer_distribution/);
assert.match(providerConfig, /sponsorship_marketplace/);
assert.match(providerConfig, /mobile_app_mediation/);
assert.match(providerConfig, /high_value_affiliate/);
assert.match(providerConfig, /crypto_web3_network/);
assert.match(providerConfig, /b2b_intent_network/);
assert.match(providerConfig, /premium_native_network/);
assert.match(providerConfig, /publisher_ssp/);
assert.match(providerConfig, /adult_network/);
assert.match(providerConfig, /XXX\/adult lane only/);
assert.match(providerConfig, /dating_affiliate/);
assert.match(providerConfig, /gambling_affiliate/);
assert.match(providerConfig, /performance_cpa/);
assert.match(providerConfig, /push_pop_network/);
assert.match(providerConfig, /explicit category opt-in/);
assert.match(providerStatus, /providerStatuses/);
assert.match(providerStatus, /workingDemandSources/);
assert.match(providerStatus, /totalMappedProviders/);
assert.match(providerStatus, /thirdPartyCanServeNow/);
assert.match(providerStatus, /nextActivationSteps/);
assert.match(providerStatus, /BuilderPerks seed\/direct approved placements/);
assert.match(netlifyConfig, /from = "\/api\/provider-status"/);
assert.match(css, /placement-card/);
assert.match(css, /impact-meter/);
assert.match(css, /score-grid/);
assert.match(extensionContent, /choosePlacement/);
assert.match(extensionContent, /Matched locally/);
assert.match(extensionContent, /api\/relevance/);
assert.match(extensionContent, /categoryFromReason/);
assert.match(extensionContent, /Hide category/);
assert.match(extensionContent, /insertTestCard/);
assert.match(extensionContent, /builderperks:show-test-card/);
assert.match(extensionContent, /builderperks-demo/);
assert.match(extensionContent, /activeAiSessionUntil/);
assert.match(extensionContent, /markActiveAiSession/);
assert.match(extensionContent, /likelySendControl/);
assert.match(extensionContent, /active AI session/);
assert.match(extensionPopup, /show-test-card/);
assert.match(extensionPopup, /First card inserted/);
assert.match(extensionPopup, /createElement\("small"\)/);
assert.doesNotMatch(extensionPopup, /innerHTML\s*=/);
assert.match(extensionManifest, /activeTab/);
assert.equal(zippedContent, extensionContent);
assert.equal(zippedPopup, extensionPopup);
assert.equal(zippedManifest, extensionManifest);
const relevanceFunction = await readFile("netlify/functions/relevance.mts", "utf8");
assert.match(relevanceFunction, /RelevanceEvent/);
assert.match(relevanceFunction, /categoryHint/);
assert.match(netlifyConfig, /from = "\/api\/relevance"/);
assert.match(netlifyConfig, /to = "\/\.netlify\/functions\/relevance"/);
assert.match(await readFile("netlify/functions/stats.mts", "utf8"), /hideCategory/);
assert.match(await readFile("netlify/functions/admin.mts", "utf8"), /needThis/);
assert.match(await readFile("netlify/functions/report.mts", "utf8"), /pilotReadout/);
assert.match(await readFile("netlify/functions/report.mts", "utf8"), /contextStored: false/);
assert.match(netlifyConfig, /from = "\/api\/report"/);
assert.match(netlifyConfig, /from = "\/api\/proof-session-nonces"/);
assert.match(netlifyConfig, /to = "\/\.netlify\/functions\/proof-session-nonces"/);
assert.match(netlifyConfig, /from = "\/api\/proof-sessions"/);
assert.match(netlifyConfig, /to = "\/\.netlify\/functions\/proof-sessions"/);

console.log("smoke ok: static app includes advertiser, placement, feedback, tracking, scoreboard, safe rendering, and local contextual matching workflows");
