import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile("public/index.html", "utf8");
const js = await readFile("public/app.js", "utf8");
const css = await readFile("public/styles.css", "utf8");
const installer = await readFile("public/install-statusline.sh", "utf8");
const statusLineHelper = await readFile("public/builderperks-statusline.sh", "utf8");
const extensionContent = await readFile("../extension/content.js", "utf8");

assert.match(html, /BuilderPerks/);
assert.match(html, /Advertiser/);
assert.match(js, /submitPlacement/);
assert.match(js, /loadPlacements/);
assert.match(js, /submitFeedback/);
assert.match(js, /submitBuilder/);
assert.match(js, /submitPublisher/);
assert.match(js, /escapeHtml/);
assert.match(js, /trackUrl/);
assert.match(js, /loadStats/);
assert.match(html, /install-statusline\.sh/);
assert.match(html, /statusline\.sh/);
assert.match(html, /offsetting tooling bills/);
assert.match(html, /not paid-to-watch traffic/);
assert.match(html, /BUILDERPERKS_VALUE_MODE/);
assert.match(html, /allowedCategories/);
assert.match(js, /install-statusline\.sh/);
assert.match(js, /publisher-earnings-count/);
assert.match(installer, /statusline\.sh/);
assert.match(installer, /preference keywords/);
assert.match(statusLineHelper, /BUILDERPERKS_PUBLISHER_ID/);
assert.match(statusLineHelper, /BUILDERPERKS_BLOCKED_KEYWORDS/);
assert.match(statusLineHelper, /BUILDERPERKS_ALLOWED_CATEGORIES/);
assert.match(statusLineHelper, /BUILDERPERKS_BLOCKED_CATEGORIES/);
assert.match(statusLineHelper, /BUILDERPERKS_VALUE_MODE/);
assert.match(statusLineHelper, /urlopen\(url, timeout=2\)/);
assert.match(await readFile("netlify/functions/placements.mts", "utf8"), /paymentStatus = "checkout_ready"/);
assert.match(await readFile("netlify/functions/placements.mts", "utf8"), /checkoutError/);
assert.match(await readFile("netlify/functions/builders.mts", "utf8"), /BuilderSignup/);
assert.match(await readFile("netlify/functions/publishers.mts", "utf8"), /Publisher/);
const adStream = await readFile("netlify/functions/ad-stream.mts", "utf8");
assert.match(adStream, /estimatedPublisherEarningsUsd/);
assert.match(adStream, /demandStatusForPlacement/);
assert.match(adStream, /builderperks_seed/);
assert.match(adStream, /blockedKeywords/);
assert.match(adStream, /matchesBlockedPreference/);
assert.match(adStream, /CATEGORY_PROFILES/);
assert.match(adStream, /allowedCategories/);
assert.match(adStream, /blockedCategories/);
assert.match(adStream, /providerLanes/);
assert.match(adStream, /regulated_partner/);
assert.match(css, /placement-card/);
assert.match(css, /impact-meter/);
assert.match(css, /score-grid/);
assert.match(extensionContent, /choosePlacement/);
assert.match(extensionContent, /Matched locally/);

console.log("smoke ok: static app includes advertiser, placement, feedback, tracking, scoreboard, safe rendering, and local contextual matching workflows");
